name: sim
channels:
  - conda-forge
dependencies:
  - jupyterlab=3.5.3
  - jupyterlab-spellchecker=0.7.3
  - matplotlib=3.7.1
  - numpy=1.25.0
  - pandas=2.0.2
  - pip=23.1.2
  - plotly=5.15.0
  - python=3.10.13
  - scipy=1.10.1
  - simpy=4.0.1
  - pip:
    - ciw==2.3.1
    - streamlit
    - sim-tools==0.3.2
    - treat-sim==1.0.0
    
